### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by UxuginPython** [RagnowProductions/Browser-Remover#1]
What about removing Firefox?

**Comment by UxuginPython** [comment]
I'm sorry, I know this is not a bug, I couldn't figure out how to tag it as a question.

**Comment by RagnowProductions** [comment]
Is Firefox For Windows firefox.exe?

**Comment by UxuginPython** [comment]
Just checked, it's C:\Program Files\Mozilla Firefox\firefox.exe

**Comment by RagnowProductions** [comment]
Ok, I Have Attached The File To This Post.

Since GitHub Doesn’t Support The File Extension That The File Is, It Is Currently In ZIP File Mode.

[FirefoxDelete.bat.zip](https://github.com/RagnowProductions/Browser-Remover/files/8749401/FirefoxDelete.bat.zip)
